### PR TITLE
Fixed support for ipaddr.js

### LINKED ISSUE #2: pinoDebugWrappedRequire returns "AssertionError: path must be a string" error
When I try and run the example server or add pino-debug to an app, this error gets returned from pinoDebugWrappedRequire....

```
ssert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: path must be a string
    at Module.require (module.js:496:3)
    at require (internal/module.js:20:19)
    at pinoDebugWrappedRequire (c:\Users\Colm-MCQS\Documents\GitHub\pino-debug\example\node_modules\ipaddr.js\li
b\ipaddr.js:14:18)
    at Object.<anonymous> (c:\Users\Colm-MCQS\Documents\GitHub\pino-debug\example\node_modules\ipaddr.js\lib\ipa
ddr.js:17:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

```

I logged out the script (the variable s) that's passed into the wrapper and the last few lines before the error is thrown is 

```
events
fresh
fs
mime
path
fs
./types.json
ms
on-finished
range-parser
path
statuses
stream
util
path
etag
proxy-addr
forwarded
ipaddr.js
[Function]
```

So the wrapper is being passed a function directly instead of a string but I can't put my finger on where it's being passed in. 

Tried this on windows and *nix, about to give it a go on Mac.

### PR DESCRIPTION
**Pull request by mcollina**
Fixes #2.

At the end, it was a missing `;`.

@davidmarkclements @colmose please have a look.

### CODE REVIEW

File: test/index.js [hunk 1]
```diff
@@ -170,6 +171,7 @@ test('when preloaded with -r, automatically logs all debug calls with log level
   module.filename = filename
   module.parent = parent
 })
+*/
```
Comment (mcollina) [inline test/index.js]: hey @davidmarkclements this test was broken before running. Not sure what happens.

Comment (davidmarkclements) [inline test/index.js]: does preloading still work though? it's just the test that's broken?

**Comment by colmose** [comment]
Bit late to the party but works a treat. :+1:
